class HtmlFormat {
  String htmlFormat =
      '<!DOCTYPE html> <html lang="en"><head> <meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Centered Image</title><style>body {display: flex;justify-content: center;align-items: center;height: 100vh;margin: 0;background-color: white;}#backgroundContainer {width: 200mm;height: 200mm;background-color: rgba(0, 0, 255, 0.4);overflow: hidden;border: 1px solid #ccc;position: relative;}#centeredImage {display: block;margin: 20mm;width: 80%;height: 80%;object-fit: contain;}#createdAtText,#locationText {position: absolute;color: white;font-size: 14px;}#createdAtText {bottom: 10mm;right: 10mm;}#locationText {bottom: 10mm;left: 10mm;}</style></head><body><div id="backgroundContainer"><img id="centeredImage" src=imageLocation alt="Centered Image"><div id="createdAtText">creationAtText</div><div id="locationText">locatioinText</div></div></body></html>';

  String htmlFormat1 = '  <!DOCTYPE html>'
      '  <html lang="en">'
      '  <head>'
      '  <meta charset="UTF-8">'
      '  <meta name="viewport" content="width=device-width, initial-scale=1.0">'
      '  <title>Centered Image</title>'
      '  <style>'
      '  #backgroundContainer {'
      '  width: 200mm;'
      '  height: 200mm;'
      '  background-color: rgba(0, 0, 255, 0.4); /* Set background color to blue with 40% transparency */'
      '  overflow: hidden;'
      '  position: relative;'
      '}'
      '#centeredImage {'
      'display: block;'
      'margin: 20mm;'
      'width: 80%;'
      'height: 80%;'
      'object-fit: cover;'
      '}'
      '#createdAtText,'
      '#locationText {'
      'position: absolute;'
      'color: white; /* Set the text color to white */'
      'font-size: 14px; /* Set the font size as needed */'
      '}'
      '#createdAtText {'
      'bottom: 10mm;'
      'right: 10mm;'
      '}'
      '#locationText {'
      'bottom: 10mm;'
      'left: 10mm;'
      '}'
      '</style>'
      '</head>'
      '<body>'
      '<div id="backgroundContainer">'
      '<img id="centeredImage" src=imageLocation alt="Centered Image"><div id="createdAtText">creationAtText</div>'
      '<div id="locationText">locatioinText</div>'
      '</div>'
      '</body>'
      '</html>';
}
